### ISSUE TITLE
Update Welcome page plugin.

### ISSUE THREAD

**Issue by m-thread** [librepilot/LibrePilot#26]
Update the Welcome page plugin to use data from LibrePilot forums for news and GitHub API for activity.

**Comment by skarlsso** [comment]
Two patches to get basic functionality up and running:
https://github.com/librepilot/LibrePilot/pull/31

**Comment by AlessioMorale** [comment]
I have also opened the followup issue #43

**Comment by skarlsso** [comment]
Closing this since #31 has been merged.
