### ISSUE TITLE
Add support for ccache

### ISSUE THREAD

**Issue by AlessioMorale** [librepilot/LibrePilot#41]

**Comment by parched** [comment]
Is ccache not already supported by default? What do you mean by this?

**Comment by AlessioMorale** [comment]
i'm adding some modifications that allows ccache to be used for both gcc_arm toolchain and qmake.
osx needed some modification because it explicitly references toolchain with absolute path

**Comment by parched** [comment]
Ok makes sense

**Comment by AlessioMorale** [comment]
Also i'm looking at windows implementation as i have a small atom tablet i use on the field:  it takes forever to compile :)
